parameters:
  - name: WorkloadName
    type: string
  - name: ServiceConnection
    type: string
  - name: Environment
    type: string
  - name: Subscription
    type: string
jobs:
  - job: Configure
    displayName: 'Configure ${{variables.Environment}} ${{variables.WorkloadName}}'
    steps:
      - checkout: self
        path: src
        submodules: true

      - task: AzureCLI@2
        displayName: 'Configure ${{variables.Environment}} ${{variables.WorkloadName}}'
        inputs:
          azureSubscription: "${{ parameters.ServiceConnection }}"
          scriptType: ps
          scriptLocation: inlineScript
          inlineScript: |
            Write-Host "Configuring ${{variables.Environment}} ${{variables.WorkloadName}} through powershell"
